---
abstract: 'tests module permissions in your distribution'
author:
  - 'Kenichi Ishigaki <ishigaki@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  Test::More: '0.88'
  Test::UseAllModules: '0.10'
configure_requires:
  ExtUtils::MakeMaker::CPANfile: '0.04'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.76, CPAN::Meta::Converter version 2.140640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Test-PAUSE-Permissions
no_index:
  directory:
    - t
    - inc
requires:
  Config::Identity: '0'
  Exporter: '0'
  PAUSE::Permissions: '0.06'
  Parse::CPAN::Meta: '0'
  Parse::LocalDistribution: '0.07'
  Parse::PMFile: '0.15'
  parent: '0'
resources:
  repository: https://github.com/charsbar/Test-PAUSE-Permissions
version: '0.01'
